name: Nwserver

on:
  workflow_dispatch:

jobs:
  nwserver:
    strategy:
      matrix:
        version: ["8193.35"]
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - uses: jiro4989/setup-nim-action@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: |
            arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Clone SteamRE/DepotDownloader
        run: |
          gh repo clone SteamRE/DepotDownloader
      # 8193.35
      - name: Download build8193.35 nwn:ee files
        env:
          APP_ID: 704450
          BUILD_ID: 9560766
          BIN_DEPOT_ID: 704454
          CONTENT_DEPOT_ID: 704451
          BRANCH: preview
          BRANCH_PASSWORD: previewpreview
        if: matrix.version == '8193.35'
        run: |
          cd DepotDownloader/DepotDownloader
          dotnet run -app $APP_ID -depot $BIN_DEPOT_ID -beta $BRANCH -betapassword $BRANCH_PASSWORD -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          dotnet run -app $APP_ID -depot $CONTENT_DEPOT_ID -beta $BRANCH -betapassword $BRANCH_PASSWORD -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd ../..
          mkdir data
          cp -r DepotDownloader/DepotDownloader/depots/$BIN_DEPOT_ID/$BUILD_ID/. data/
          cp -r DepotDownloader/DepotDownloader/depots/$CONTENT_DEPOT_ID/$BUILD_ID/. data/

          mkdir -p docker_data/bin/x86
          cp data/bin/linux-x86/nwserver-linux docker_data/bin/x86/nwserver-linux

          mkdir -p docker_data/bin/arm64
          cp data/bin/linux-arm64/nwserver-linux docker_data/bin/arm64/nwserver-linux

          mkdir -p docker_data/lang/en/data
          cp data/lang/en/data/dialog.tlk docker_data/lang/en/data/dialog.tlk
      - run: |
          nimble install neverwinter -y
          nwn_resman_pkgsrv -d docker_data/data -k data/nwn_base

          ls docker_data/bin
          ls docker_data/lang
          ls docker_data/data
      # docker
      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: nwserver
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: nwnrs/nwserver:${{ matrix.version }}
