name: Nwserver

on: push

jobs:
  nwserver:
    strategy:
      matrix:
        version: ["8193.35"]
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - uses: jiro4989/setup-nim-action@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: |
            arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Clone SteamRE/DepotDownloader
        run: |
          gh repo clone SteamRE/DepotDownloader
      - name: Install Neverwinter.nim
        run: |
          nimble install neverwinter -y
          echo "~/.nimble/bin" >> $GITHUB_PATH
      # 8193.35
      - name: Download build8193.35 nwn:ee files
        env:
          APP_ID: 704450
          BUILD_ID: 9601420
          BIN_DEPOT_ID: 704454
          CONTENT_DEPOT_ID: 704451
          BRANCH: preview
          BRANCH_PASSWORD: previewpreview
          NWN_ROOT: ./
        if: matrix.version == '8193.35'
        run: |
          mkdir -p docker_data/data/data docker_data/lang/en/data docker_data/data/bin/linux-x86 docker_data/data/bin/linux-arm64
          cd DepotDownloader/DepotDownloader
          dotnet run -app $APP_ID -depot $BIN_DEPOT_ID -beta $BRANCH -betapassword $BRANCH_PASSWORD -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          dotnet run -app $APP_ID -depot $CONTENT_DEPOT_ID -beta $BRANCH -betapassword $BRANCH_PASSWORD -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd depots/$CONTENT_DEPOT_ID/$BUILD_ID/
          nwn_resman_pkg -d $GITHUB_WORKSPACE/docker_data/data/data
          cd $GITHUB_WORKSPACE/nwserver
          cp ../DepotDownloader/DepotDownloader/depots/$BIN_DEPOT_ID/$BUILD_ID/bin/linux-x86/nwserver-linux docker_data/data/bin/linux-x86/nwserver-linux
          cp ../DepotDownloader/DepotDownloader/depots/$BIN_DEPOT_ID/$BUILD_ID/bin/linux-arm64/nwserver-linux docker_data/data/bin/linux-arm64/nwserver-linux
          cp ../DepotDownloader/DepotDownloader/depots/$CONTENT_DEPOT_ID/$BUILD_ID/data/cacert.pem docker_data/data/data/cacert.pem
          cp ../DepotDownloader/DepotDownloader/depots/$CONTENT_DEPOT_ID/$BUILD_ID/lang/en/data/dialog.tlk docker_data/lang/en/data/dialog.tlk
          cp scripts/. docker_data/
          cp module/. docker_data/data/data/mod/
      # docker
      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: nwserver
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: nwnrs/nwserver:${{ matrix.version }}
