name: Generate

on:
  workflow_dispatch:

jobs:
  nwserver:
    strategy:
      matrix:
        version: ["8193.35"]
        platform: ["linux-x86", "linux-arm64"]
    name: Generate ${{ matrix.platform }} ${{ matrix.version }} dockerfile
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Clone SteamRE/DepotDownloader
        run: |
          gh repo clone SteamRE/DepotDownloader

      # 8193.35
      - name: Download build8193.35 nwn:ee files
        if: ${{ matrix.version }} == '8193.35'
        run: |
          cd DepotDownloader/DepotDownloader
          dotnet run -app 704450 -depot 704454 -beta ${{ github.event.inputs.release }} -betapassword previewpreview -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd ${{ env.GITHUB_WORKSPACE }}
          cp -r DepotDownloader/DepotDownloader/depots/704454/7843474/ data
          ls data