name: Nwserver

on:
  workflow_dispatch:

jobs:
  nwserver:
    strategy:
      matrix:
        version: ["8193.35"]
        platform: ["linux-x86", "linux-arm64"]
    name: ${{ matrix.version }} ${{ matrix.platform }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Clone SteamRE/DepotDownloader
        run: |
          gh repo clone SteamRE/DepotDownloader
      # 8193.35
      - name: Download build8193.35 nwn:ee files
        if: ${{ matrix.version }} == '8193.35'
        run: |
          cd DepotDownloader/DepotDownloader
          dotnet run -app 704450 -depot 704454 -beta preview -betapassword previewpreview -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd ../..
          cp -r DepotDownloader/DepotDownloader/depots/704454/9560766/ nwserver/data
          ls nwserver/data/bin
      # x86
      - name: Building x86 nwserver
        if: ${{ matrix.platform }} == 'linux-x86'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NWN_ARCH=${{ matrix.platform }}
          context: nwserver
          platforms: linux/amd64
          push: true
          tags: nwnrs/nwserver:${{ matrix.version }}
      # arm64
      - name: Building arm64 nwserver
        if: ${{ matrix.platform }} == 'linux-arm64'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NWN_ARCH=${{ matrix.platform }}
          context: nwserver
          platforms: linux/arm64
          push: true
          tags: nwnrs/nwserver:${{ matrix.version }}
